### PR TITLE
Updated configs to play better with GPU backend

### PR DESCRIPTION
**Pull request by ssrothman**
@kpedro88 notified me that the torchscript configs in this repo were not compatible with the Sonic Pytorch GPU backend. This update fixes this compatibility. Note that none of the weights or actual model behavior have changed. This is just a minor syntactic change in the torchscript code.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
* pull_requests = https://github.com/cms-sw/cmsdist/pull/8324, https://github.com/cms-data/HeterogeneousCore-SonicTriton/pull/2, https://github.com/cms-sw/cmssw/pull/40814, https://github.com/cms-data/RecoEcal-EgammaClusterProducers/pull/3
* workflows = 10805.31

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@cms-sw/reconstruction-l2 we must bypass your signature because the PR that need this external was already merged, sorry for that. Follow up in issue https://github.com/cms-sw/cmssw/issues/40938

**Comment by perrotta** [comment]
merge

**Pull request merged**
