### PR TITLE
Fix weights to be identical to original commit

### PR DESCRIPTION
**Pull request by ssrothman**
When updating the model files in the previous PR I accidentally used weights from a different training. The physics performance between the two trainings is identical, but for consistency this PR reverts the weights to be identical with the original training.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
* workflows = 10805.31

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
please test
- wf 10805.31 shows now differences wrt CMSSW_13_1_X_2023-03-02-1100 plus the original PRs that this one is supposed to fix: I would have expected none...
- Let try to test once again on top of a clean CMSSW_13_1_X_2023-03-02-2300: here I would expect to see reverted the differences observed for #40814

**Comment by perrotta** [comment]
@ssrothman @kpedro88 

- the [first tests](https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/3#issuecomment-1452737845) included both the original  cms-data PR (https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2) and this one, which should kind of revert it, since it reverts the weights to be identical with the original training, as you write. However the test results showed that the previous figures weren't restored as expected:
image
image

- To cross check I run some [further tests](https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/3#issuecomment-1453452167) on keeping CMSSW_13_1_X_2023-03-02-2300 as baseline, which contains https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2. The results of that comparison should have shown the opposite of the modifications reported for the original PR: this is not the case, instead.

- Let me add here the configurations (from https://github.com/cms-sw/cmssw/pull/40814#issuecomment-1450796118) which we are expected to revert would this PR really revert the weights to be identical with the original training, so that they can be saved even when the test results will disappear
image
image

- Evidently, this fix does not reverts the weights to be pretty identical with the original training. Perhaps also for the other cms-data PRs merged together with https://github.com/cms-sw/cmssw/pull/40814 weights from a different training were used? E.g.
  - https://github.com/cms-data/HeterogeneousCore-SonicTriton/pull/2
  - https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2
  - https://github.com/cms-data/RecoEcal-EgammaClusterProducers/pull/3
- Or maybe the new vesion of the Triton client, https://github.com/cms-sw/cmsdist/pull/8324, does originate some (kind of random) modification in the results with respect to the previous one?

**Comment by perrotta** [comment]
@ssrothman @kpedro88 any news on this? None of you was present at the [today's ORP meeting](https://indico.cern.ch/event/1262541/), where this issue was addressed...
Is there some better understanding of the issue by now?

**Comment by kpedro88** [comment]
@perrotta apologies, I'm away at a workshop this week.

We also saw this behavior in our private tests last week and realized that there is some randomness inherent to the network itself. The random behavior has been there all along, but http://github.com/cms-sw/cmssw/pull/40814 may actually have been the first time that comparison tests were run for 10805.31 (since it is not part of the short matrix), so it wasn't noticed before. This PR does correctly restore the original weights, but we need to make some more changes to make the network deterministic (this is a work in progress right now).

**Comment by perrotta** [comment]
@ssrothman @kpedro88 
As a cross-check, I made bot running the comparisons for the wf  10805.31 in [another PR](https://github.com/cms-sw/cmssw/pull/40666#issuecomment-1469913694) which is completely uncorrelated from the update of these weights. And the outcome is exactly as what you say here, that is there is some randomness in the results which is inherent to the network itself. The "randomness" seems quite significant, i.e. not just a numerical fluctuation in the last digi somewhere.

Therefore:
- Let merge this PR with the correct weights, as you verified independently
- Open a github issue to take record of the progresses in the solution of this "randomness" problem

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
