### PR TITLE
SonicTriton configs and weights files for UL18 DRN regression

### PR DESCRIPTION
**Pull request by ssrothman**
This PR adds the necessary configs and weights for the UL18 DRN regression in cmssw [PR #37134](https://github.com/cms-sw/cmssw/pull/37134).

### CODE REVIEW

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37134#issuecomment-1099696013

**Comment by ssrothman** [comment]
What is the cause of this error? What can I do to resolve it?

**Comment by smuzaffar** [comment]
@ssrothman , error is not related to this pull request ( see https://github.com/cms-sw/cmssw/issues/37584 )

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1
- Tested together with https://github.com/cms-sw/cmssw/pull/37134

**Comment by perrotta** [comment]
merge

**Pull request merged**
